In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\windows\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\windows\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\windows\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\windows\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\windows\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\windows\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
print(pd.__version__)

2.3.3

In [12]:
df = pd.read_csv("telecom_churn_clean.csv")

In [13]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,tenureGroup,PhoneService,MultipleLines,InternetService,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,HighValueCustomer,TotalCharges,CleanedTotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,0-1 Year,No,No phone service,DSL,...,No,No,Month-to-month,Yes,Electronic check,29.85,Standard,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,2-4 Years,Yes,No,DSL,...,No,No,One year,No,Mailed check,56.95,Standard,1889.50,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,0-1 Year,Yes,No,DSL,...,No,No,Month-to-month,Yes,Mailed check,53.85,Standard,108.15,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,2-4 Years,No,No phone service,DSL,...,No,No,One year,No,Bank transfer (automatic),42.30,Standard,1840.75,1840.75,No
4,9237-HQITU,Female,0,No,No,2,0-1 Year,Yes,No,Fiber optic,...,No,No,Month-to-month,Yes,Electronic check,70.70,Standard,151.65,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,1-2 Years,Yes,Yes,DSL,...,Yes,Yes,One year,Yes,Mailed check,84.80,High Value,1990.50,1990.50,No
7039,2234-XADUH,Female,0,Yes,Yes,72,4+ Years,Yes,Yes,Fiber optic,...,Yes,Yes,One year,Yes,Credit card (automatic),103.20,High Value,7362.90,7362.90,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,0-1 Year,No,No phone service,DSL,...,No,No,Month-to-month,Yes,Electronic check,29.60,Standard,346.45,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,0-1 Year,Yes,Yes,Fiber optic,...,No,No,Month-to-month,Yes,Mailed check,74.40,Standard,306.60,306.60,Yes
7042,3186-AJIEK,Male,0,No,No,66,4+ Years,Yes,No,Fiber optic,...,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,High Value,6844.50,6844.50,No

In [14]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,tenureGroup,PhoneService,MultipleLines,InternetService,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,HighValueCustomer,TotalCharges,CleanedTotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,0-1 Year,No,No phone service,DSL,...,No,No,Month-to-month,Yes,Electronic check,29.85,Standard,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,2-4 Years,Yes,No,DSL,...,No,No,One year,No,Mailed check,56.95,Standard,1889.50,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,0-1 Year,Yes,No,DSL,...,No,No,Month-to-month,Yes,Mailed check,53.85,Standard,108.15,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,2-4 Years,No,No phone service,DSL,...,No,No,One year,No,Bank transfer (automatic),42.30,Standard,1840.75,1840.75,No
4,9237-HQITU,Female,0,No,No,2,0-1 Year,Yes,No,Fiber optic,...,No,No,Month-to-month,Yes,Electronic check,70.70,Standard,151.65,151.65,Yes

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customerID           7043 non-null   object
 1   gender               7043 non-null   object
 2   SeniorCitizen        7043 non-null   int64
 3   Partner              7043 non-null   object
 4   Dependents           7043 non-null   object
 5   tenure               7043 non-null   int64
 6   tenureGroup          7043 non-null   object
 7   PhoneService         7043 non-null   object
 8   MultipleLines        7043 non-null   object
 9   InternetService      7043 non-null   object
 10  OnlineSecurity       7043 non-null   object
 11  OnlineBackup         7043 non-null   object
 12  DeviceProtection     7043 non-null   object
 13  TechSupport          7043 non-null   object
 14  StreamingTV          7043 non-null   object
 15  StreamingMovies      7043 non-null   object
 16  Contract             7043 non-null   object
 17  PaperlessBilling     7043 non-null   object
 18  PaymentMethod        7043 non-null   object
 19  MonthlyCharges       7043 non-null   float64
 20  HighValueCustomer    7043 non-null   object
 21  TotalCharges         7032 non-null   float64
 22  CleanedTotalCharges  7043 non-null   float64
 23  Churn                7043 non-null   object
dtypes: float64(3), int64(2), object(19)
memory usage: 1.3+ MB

In [16]:
df.describe()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,CleanedTotalCharges
count,7043.000000,7043.000000,7043.000000,7032.000000,7043.000000
mean,0.162147,32.370013,64.761692,2283.300441,2279.665491
std,0.368612,24.560955,30.090047,2266.771362,2266.862669
min,0.000000,0.000000,18.250000,18.800000,0.000000
25%,0.000000,9.000000,35.500000,401.450000,398.550000
50%,0.000000,29.000000,70.350000,1397.475000,1394.550000
75%,0.000000,55.000000,89.850000,3794.737500,3786.600000
max,1.000000,72.000000,118.750000,8684.800000,8684.800000

In [17]:
df.describe(include='all')

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,tenureGroup,PhoneService,MultipleLines,InternetService,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,HighValueCustomer,TotalCharges,CleanedTotalCharges,Churn
count,7043,7043,7043.000000,7043,7043,7043.000000,7043,7043,7043,7043,...,7043,7043,7043,7043,7043,7043.000000,7043,7032.000000,7043.000000,7043
unique,7043,2,NaN,2,2,NaN,4,2,3,3,...,3,3,3,2,4,NaN,2,NaN,NaN,2
top,7590-VHVEG,Male,NaN,No,No,NaN,4+ Years,Yes,No,Fiber optic,...,No,No,Month-to-month,Yes,Electronic check,NaN,Standard,NaN,NaN,No
freq,1,3555,NaN,3641,4933,NaN,2239,6361,3390,3096,...,2810,2785,3875,4171,2365,NaN,4366,NaN,NaN,5174
mean,NaN,NaN,0.162147,NaN,NaN,32.370013,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,64.761692,NaN,2283.300441,2279.665491,NaN
std,NaN,NaN,0.368612,NaN,NaN,24.560955,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,30.090047,NaN,2266.771362,2266.862669,NaN
min,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,18.250000,NaN,18.800000,0.000000,NaN
25%,NaN,NaN,0.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,35.500000,NaN,401.450000,398.550000,NaN
50%,NaN,NaN,0.000000,NaN,NaN,29.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,70.350000,NaN,1397.475000,1394.550000,NaN
75%,NaN,NaN,0.000000,NaN,NaN,55.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,89.850000,NaN,3794.737500,3786.600000,NaN
max,NaN,NaN,1.000000,NaN,NaN,72.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,118.750000,NaN,8684.800000,8684.800000,NaN

In [18]:
df.isnull().sum()

customerID              0
gender                  0
SeniorCitizen           0
Partner                 0
Dependents              0
tenure                  0
tenureGroup             0
PhoneService            0
MultipleLines           0
InternetService         0
OnlineSecurity          0
OnlineBackup            0
DeviceProtection        0
TechSupport             0
StreamingTV             0
StreamingMovies         0
Contract                0
PaperlessBilling        0
PaymentMethod           0
MonthlyCharges          0
HighValueCustomer       0
TotalCharges           11
CleanedTotalCharges     0
Churn                   0
dtype: int64

In [19]:
df["TotalCharges"]=df.groupby('tenure')['TotalCharges'].transform(lambda x: x.fillna(x.median()))

In [20]:
df.isnull().sum()

customerID             0
gender                 0
SeniorCitizen          0
Partner                0
Dependents             0
tenure                 0
tenureGroup            0
PhoneService           0
MultipleLines          0
InternetService        0
OnlineSecurity         0
OnlineBackup           0
DeviceProtection       0
TechSupport            0
StreamingTV            0
StreamingMovies        0
Contract               0
PaperlessBilling       0
PaymentMethod          0
MonthlyCharges         0
HighValueCustomer      0
TotalCharges           0
CleanedTotalCharges    0
Churn                  0
dtype: int64

In [31]:
df.columns=df.columns.str.lower()

In [32]:
df.columns

Index(['customerid', 'gender', 'seniorcitizen', 'partner', 'dependents',
       'tenure', 'tenuregroup', 'phoneservice', 'multiplelines',
       'internetservice', 'onlinesecurity', 'onlinebackup', 'deviceprotection',
       'techsupport', 'streamingtv', 'streamingmovies', 'contract',
       'paperlessbilling', 'paymentmethod', 'monthlycharges',
       'highvaluecustomer', 'cleanedtotalcharges', 'churn'],
      dtype='object')

In [24]:
df.columns=df.columns.str.title()

In [25]:
df.columns

Index(['Customerid', 'Gender', 'Seniorcitizen', 'Partner', 'Dependents',
       'Tenure', 'Tenuregroup', 'Phoneservice', 'Multiplelines',
       'Internetservice', 'Onlinesecurity', 'Onlinebackup', 'Deviceprotection',
       'Techsupport', 'Streamingtv', 'Streamingmovies', 'Contract',
       'Paperlessbilling', 'Paymentmethod', 'Monthlycharges',
       'Highvaluecustomer', 'Totalcharges', 'Cleanedtotalcharges', 'Churn'],
      dtype='object')

In [33]:
df=df.drop('Totalcharges',axis=1)

KeyError: "['Totalcharges'] not found in axis"

In [ ]:
df.columns

In [28]:
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\windows\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\windows\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\windows\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\windows\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [34]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "postgres"
password = quote_plus("Lalitha@2026")   # 🔑 encode special characters
host = "localhost"
port = "5432"
database = "telecom_churn"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

# Test connection
with engine.connect() as conn:
    print("Connected successfully!")

df.to_sql(
    "customer",
    engine,
    if_exists="replace",
    index=False
)

print("Data successfully loaded into PostgreSQL")

Connected successfully!
Data successfully loaded into PostgreSQL